/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// AuthenticateUserByName : The authenticate user by name request body.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticateUserByName {
    /// Gets or sets the username.
    #[serde(rename = "Username")]
    pub username: String,
    /// Gets or sets the plain text password.
    #[serde(rename = "Pw")]
    pub pw: String,
}
